### YamlMime:UniversalReference
ms.openlocfilehash: 777051058935475aebf2055932882ec0cd21fea9
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 12/13/2018
ms.locfileid: "52135174"
items:
- uid: azure-servicefabric.TestErrorChaosEvent
  name: TestErrorChaosEvent
  fullName: TestErrorChaosEvent
  children:
  - azure-servicefabric.TestErrorChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: >-
    Décrit un événement de Chaos est généré lorsqu’un événement inattendu se produit dans le moteur de Chaos.

    Par exemple, en raison de l’instantané de cluster étant incohérent, lors de la défaillance d’une entité, le Chaos trouvé que l’entité a déjà généré une erreur--qui serait un événement inattendu.
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.TestErrorChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: Décrit pourquoi TestErrorChaosEvent a été généré. Par exemple, le Chaos tente une partition de l’erreur mais détecte que la partition n’est plus une tolérance de panne, puis un TestErrorEvent est généré avec la raison indiquant que la partition n’est pas une tolérance de panne.
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
